City-of-Helsinki/infraohjelmointi-api

infraohjelmointi_api/serializers.py
Change to projectCreateSerializer to have projectReadiness returned with response in a Post or Patch request
=> Serializer modified to have projectReadiness field on post/patch request

infraohjelmointi_api/tests/test_ProjectHashTags.py, infraohjelmointi_api/views.py
Changed response of /project-hashtags endpoint
- Returns top 15 hashtags alongside all hashtags
- Override list action of hashtag viewset
- If no hashtags have been assigned to a project, popularHashtags list is empty
- Each time hashtags are fetched, popular hashtags are calculated according to how many projects are using each hashtag
- Tests written to test hashtags endpoint and popular hashtags functionality
=> Story/io 231/calculate popular hashtags

infraohjelmointi_api/serializers.py, infraohjelmointi_api/tests/test_ProjectGroups.py, infraohjelmointi_api/tests/test_Projects.py, infraohjelmointi_api/views.py
- Changed response for projects endpoint when "freeSearch" query parameter is used
- Created DynamicFieldsModelSerializer Class which allows fields to be retrieved from serializers dynamically
- "freeSearch" query parameter matches string with project name, hashtag name and group name and returns a response
- Added projectGroup as a query parameter to project filtering
- Added test for projectGroup parameter
=> Story/io 245/free search endpoint alter project filter

infraohjelmointi_api/management/commands/util/hierarchy.py, infraohjelmointi_api/services/ProjectGroupService.py
Renamed districtRelation to locationRelation in ProjectGroupService and all its references in management commands
=> Fixed ProjectGroup field name, districtRelation -> locationRelation

infraohjelmointi_api/tests/test_Projects.py, infraohjelmointi_api/views.py
- Move search results to its own endpoint
- Added direct, limit, and  year query parameter to projects endpoint
- direct url query param makes sure projects filtered by location/class only contain projects directly under that class/location
- limit param used to control the number of projects in response
- year param returns projects with the provided year financial data
=> Story/io 281/planning view projects endpoint

infraohjelmointi_api/serializers.py, infraohjelmointi_api/tests/test_ProjectGroups.py, infraohjelmointi_api/views.py
Fixed delete request response to have the id of the deleted group
Fixed a logical error in project group validation which would throw an error if a group was patched with a project which exists on the group itself.
Override update function of ProjectGroupSerializer to remove projects which are not in the patch request
=> Project group delete request response changes and more

infraohjelmointi_api/tests/test_Projects.py, infraohjelmointi_api/views.py
- Override the destroy method on ProjectView to change the response of the DELETE request
- Added deleted project id in the DELETE request response on the project endpoint
- Wrote test to check for the id in response
- Removed a duplicate delete project test
=> Delete project response change

infraohjelmointi_api/serializers/FinancialSumSerializer.py, infraohjelmointi_api/signals.py, infraohjelmointi_api/tests/test_Projects.py, infraohjelmointi_api/validators/ProjectFinancialValidators/LockedFieldsValidator.py, infraohjelmointi_api/views/ConstructionPhaseDetailViewSet.py, infraohjelmointi_api/views/ConstructionPhaseViewSet.py, infraohjelmointi_api/views/PlanningPhaseViewSet.py, infraohjelmointi_api/views/ProjectAreaViewSet.py, infraohjelmointi_api/views/ProjectCategoryViewSet.py, infraohjelmointi_api/views/ProjectClassViewSet.py, infraohjelmointi_api/views/ProjectLocationViewSet.py, infraohjelmointi_api/views/ProjectPhaseViewSet.py, infraohjelmointi_api/views/ProjectPriorityViewSet.py, infraohjelmointi_api/views/ProjectQualityLevelViewSet.py, infraohjelmointi_api/views/ProjectResponsibleZoneViewSet.py, infraohjelmointi_api/views/ProjectRiskViewSet.py, infraohjelmointi_api/views/ProjectTypeViewSet.py, infraohjelmointi_api/views/ProjectViewSet.py, project/settings.py
- Optimised finance calculations by caching them in local memory for 24 hours
- Added functionality to reset changed calculations in the cache through signals
- Enabled caching on endpoints with values which don't often change
- Changed frameBudget calculations by moving some of them to Pandas to account for location levels under classes
- Fixed an issue where finance change in future or past levels would give back wrong information in finance-update event
- Fixed issue for multiple finance update events being sent to the FE on timeline move
- Fixed tests to pass
=> Story/io 369/finance events and calculations optimizations

infraohjelmointi_api/serializers/FinancialSumSerializer.py
- Fixed frameBudget overlap alert
- Now frameBudget alert icon should only pop up if the sum of frame budgets of classes/locations directly under the class is bigger than the frame budget
- Ticket: [https://futurice.atlassian.net/browse/HKISD-8](https://futurice.atlassian.net/browse/HKISD-8)
=> Fix: frameBudget overlap alert

README.md
- Update README about how to populate `infraohjelmointi_api_project.projectDistrict_id` column after #106 release
- With this projects will get Suurpiiri data on project cards.
=> Update README how to populate projectDistrict_id column

infraohjelmointi_api/management/commands/util/BudgetFileHandler.py
Previously importer did not add budget numbers under column 2023 because it was planned like that. With this PR this is now removed.
=> After file import show budgets on UI from 2024 forward

fix-database.sql, infraohjelmointi_api/management/commands/util/BudgetFileHandler.py, infraohjelmointi_api/management/commands/util/hierarchy.py
- Remove "suurpiiri" string from _projectlocation_ table _path_ column
- Helps adding data to _project_ and _projectgroup_ tables _projectDistrict_id_ and _location_id_ columns 
To test locally:
- rebuild API from zero (docker-compose down --volumes && docker-compose up)
- import excels (hierarchy and projects)
- import project location options with manage.py (locationimporter)
- run update-districts.sql on PSQL to populate projectDistrict_id and location_id columns 
- ! check that local environment is similar as prod location
- run fix-database.sql on PSQL
- import excels which adds missing locations on hierarchy
To check:
- Hierarchies and projects look normal
- no duplicates and some names includes word "suurpiiri"
- Hierarchy includes new empty locations
- When project card is opened, …
=> HKISD-41: change hierarchy import and queries

infraohjelmointi_api/serializers/FinancialSumSerializer.py
https://futurice.atlassian.net/browse/HKISD-48
When user deleted a project, numbers were not updated because they were cached in the backend for 24 hours.
=> HKISD-48: Delete caching for summed finances

infraohjelmointi_api/services/ProjectFinancialService.py, infraohjelmointi_api/views/ProjectViewSet.py
- There was a bug in saving the finances for a project, where if the finance year was outside startyear + 10 years, it gave a key error and the saving failed
- Code is now refactored so that finances can be saved to any year from the start year (start of timeline in UI) instead of just 10 years from it.
- UI PR about the same issue: https://github.com/City-of-Helsinki/infraohjelmointi-ui/pull/154
=> HKISD-28: fix project card finance save

.gitignore, infraohjelmointi_api/management/commands/util/hierarchy.py
- Previously when hierarchy was imported, it created ProjectLocation table with incorrect path values.
- When "Östersundomin suurpiiri" was imported, it set "Östersundomin" as the path. Correct path would be "Östersundom".
=> Set correct string as path when importing files on the first time

infraohjelmointi_api/views/ProjectViewSet.py
When project's finance value was set to zero, code understood INT value "0" as False and did not save the value correctly to database.
> In Python, the integer 0 is always False, while every other number, including negative numbers, are True. In fact, under the hood, booleans inherit from integers.
https://www.learnpython.dev/02-introduction-to-python/090-boolean-logic/10-truthiness/#numbers
=> Save finance value correctly if set zero

infraohjelmointi_api/services/utils/ProjectWiseDataMapper.py
While investigating HKISD-70 on PROD environment, I noticed old debug message that created error messages. Error messages comes when Logger tries to convert Person object to string which it failed to do. 
With this PR the error causing debug line will be removed.
An example of failed Logging error (Person object is empty):
```
--- Logging error ---
Traceback (most recent call last):
File "/usr/lib/python3.11/logging/__init__.py", line 1110, in emit
msg = self.format(record)
^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/logging/__init__.py", line 953, in format
return fmt.format(record)
^^^^^^^^^^^^^^^^^^
File "/app/project/customlogging/ColoredFormatter.py", line 27, in format
return formatter.format(record)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/logging/__init__.py", line …
```
=> HKISD-70: Remove not needed old debug message when mapping PW data

infraohjelmointi_api/serializers/FinancialSumSerializer.py
https://futurice.atlassian.net/browse/HKISD-57
When a project is moved to a new class, the numbers aren't summed correctly as you can see in the image below:
This happens because there is a problem with updating the cache. We could temporarily change the cache length to two hours so that the numbers would update quicker and the users wouldn't have to wait for one day before seeing the new values. We need to prioritize other features at the moment so we will get back to this issue later.
=> HKISD-57: temporary fix for the cache

infraohjelmointi_api/management/commands/util/hierarchy.py
https://futurice.atlassian.net/browse/HKISD-81
On coordinator field under class **803 01** few subclasses and districts were missing codes A, B, C, ...
This change adds codes on names when the project is set up first time locally while importing hierarchy excel file. The change affects only the names.
The excel file is update on the secret vault.
=> HKISD-81: Add codes for classes and hierarchies on coord view if set on hierarchy import file.

infraohjelmointi_api/permissions.py
This PR will add project managers permissions also to create new notes for projects. Project manager is allowed to do any actions to notes: read, create, modify and delete. 
Also removed personPlanning and personConstruction from the list of restrictions to project managers.
=> Hkisd 124/fix note adding permissions for project manager

infraohjelmointi_api/permissions.py
- Users with viewer roles are allowed to see project cards now so they needed access to fetch the project object
- ticket: [https://helsinkisolutionoffice.atlassian.net/browse/IO-387](https://helsinkisolutionoffice.atlassian.net/browse/IO-387)
- Instruction for testing can be found from the UI PR: [https://github.com/City-of-Helsinki/infraohjelmointi-ui/pull/255](https://github.com/City-of-Helsinki/infraohjelmointi-ui/pull/255)
=> feat: IO-387 add rights for viewers to fetch project objects

README.md
Improve documentation
- move the section about optional import commands to the bottom
- remove unnecessary 'prefix' from SQL import command
=> docs: make readme easier to follow while following data import steps

infraohjelmointi_api/views/api/ApiProjectsViewSet.py
Previously updated projects were not listed when fetching all projects using the API `/projects` endpoint. The API fetched the information only once, and used the same result for other `/projects` endpoint fetches.
This issue is visible only for the this specific endpoint. Other endpoints such as `/projects/<id>` (to fetch specific project object) returned updated values.
The fix forces to get all project objects.
=> HKISD-179/fetch updated projects successfully

Dockerfile, requirements.txt
- Switch from Docker Hub image to Red Hat Ecosystem Catalog image to fix issues with blocked image fetches from Docker Hub.
- Rewrite dockerfile
- Change boolean value to string, because docker-compose does not allow boolean value type
How-to test:
Run docker-compose up --build --force-recreate
This force-re-builds the image
If it fails, it might happen because image caches. Cleaning docker builder caches requires deleting all images
docker-compose down - Stop and remove all docker-compose containers (doesn't delete volumes)
=> Update dockerfile to redhat image

Dockerfile
Set specific version for the Python image. The issue about version tag `:latest` was raised by SonarCloud check.
=> build: set specific version for the ubi9-python image

docker-entrypoint.sh, project/settings.py
Twisted (and therefore daphne) defaults to a max line length of 16384. This is not enough due to a relatively long Authentication header created by helsinki-tunnistus for certain AD users that have many AD groups. It is possible to change this config directly in twisted during runtime, but it is not configurable in daphne itself.
=> fix: add configurable TWISTED_MAX_LINE_LENGTH setting

project/settings.py
Twisted (and therefore daphne) defaults to a max line length of 16384. This is not enough due to a relatively long Authentication header created by helsinki-tunnistus for certain AD users that have many AD groups. It is possible to change this config directly in twisted during runtime, but it is not configurable in daphne itself.
--
This is a cherry-pick from develop branch. Dev/test build pipelines are not working, and Platta doesn't know when those will be fixed, so as this change is needed urgently to main, this cherry-pick was made.
=> fix: HKISD-184 add configurable TWISTED_MAX_LINE_LENGTH setting

infraohjelmointi_api/management/commands/locationimporter.py
- added a script to add "Eri suurpiirejä location option
- UI PR: https://github.com/City-of-Helsinki/infraohjelmointi-ui/pull/278
- to test:
in the ap docker container first run
`python manage.py locationimporter --eri-suurpiirejä`
and then
`python manage.py locationimporter --eri-kaupunginosia`
Check from the UI that the district menu on a project card has "Eri suurpiirejä" option and when that is selected, division menu has only one option and it's "Eri kaupunginosia"
=> HKISD-159 add eri suurpiirejä location option

infraohjelmointi_api/management/commands/responsiblepersons.py, infraohjelmointi_api/services/PersonService.py, infraohjelmointi_api/tests/__init__.py, infraohjelmointi_api/tests/management/commands/test_responsiblepersons.py, infraohjelmointi_api/tests/test_Person.py
KaPu app requires email addresses for responsible persons. The script, that was used to import new responsible persons, did not have the feature to include emails.
With this change, the imported excel requires three columns: first name, last name, and email.
If the email address is incorrect (is checked if the string does not have symbol '@') or empty, the data will not be added. Also, all data that was not added, will be shown at the end of the run.
```
/app $ python manage.py responsiblepersons --file .uusi/name_import.xlsx 
2024-09-16 10:28:19,500 INFO /app/infraohjelmointi_api/management/commands/responsiblepersons.py:95 Person added: Touko Testi1, email 'abc@a.fi' (00b9f68b-dbbb-4ff1-94e7-91128d0908ae)
2024-09-16 10:28:19,501 INFO …
```
=> HKISD-171/import responsible persons script email

README.md
Current README in `develop` has a small issue with code block, which this PR fixes.
Image:
=> docs: fix code block so it is shown on GitHub correctly

update-costForecast.sql
Updated: Rounded all costForecast numbers to whole numbers.
This is needed to be done prior to running the next PR which is a migration from decimal to int
=> HKSID-133 Rounded all costForecasts in db

infraohjelmointi_api/services/SapApiService.py, infraohjelmointi_api/services/SapCostService.py
Fixes the ValueError issue when trying to create or get a SapCost data without project ID UUID.
=> fix: HKISD-149 set project ID to None if SAP cost for project group

sync-from-sap.sh
Cronjob in openshift has been failing since either django update or image change.
Error is not in cronjob itself. Cronjob is running the script and that script is running file sapsynchronizer.py. In this file django module was searched from path /usr/local/bin/python, this PR changes it to /opt/app-root/bin/python. 
In /usr/local/bin/python there is no django, which is the reason for error in cronjob: cannot find module django. 
You can check the error by running in the openshift terminal:
` /app/sync-from-sap.sh`
In this branch run
` docker-compose up --build --force-recreate`
Then when docker is running check that in /opt/app-root/bin/python there is django by running this command inside the container:
` /opt/app-root/bin/python -m pip list`
You can see Django 4.2 there.
Then you can …
=> HKISD-149: fix path to python/django

infraohjelmointi_api/services/SapApiService.py
There is a bug if project has planning start year in the future. Then function get_project_costs_and_commitments_from_sap in returning empty object {}, and that was not handled in the code. 
If planning start year is in the future and empty object is received (line 77), then `'all_sap_data' in sap_costs_and_commitments and 'current_year' in sap_costs_and_commitments` is false, nothing is saved to database.
=> HKISD-229: fix bug when planning start in future

infraohjelmointi_api/management/commands/fetchsapdatabyyear.py, infraohjelmointi_api/management/commands/sapsynchronizer.py, infraohjelmointi_api/services/SapApiService.py, infraohjelmointi_api/tests/test_SAP.py, sonar-project.properties
Adding script as a file fetchsapdatabyyear.py to handle sap fetch for certain year (given as a parameter). Script can be used from command line with
`python manage.py fetchsapdatabyyear --year <year>` 
Changes to SapApiService are done with thinking the future "tilinpäätös" (financial statement) feature for admin users. When implementing this new feature in the future, function sync_all_projects_from_sap can be called with arguments `for_financial_statement and sap_year = True`
`sap_year = year of the financial statement `
and then sap data is fetched only for that given year. 
SapApiService is now taking two new arguments, for_financial_statement and sap_year. When for_financial_statement is true, also wanted year is given as argument. Then sap fetch is done only for that given year. …
=> HKISD-255: add script to fetch sap data for certain year

infraohjelmointi_api/services/SapApiService.py, infraohjelmointi_api/tests/test_SAP.py
Previously all sap data was fetched from the start of the planning year. 
This is now changed so, that start date for all data fetching is 1.1.2017. 
You can test this locally with this branch:
- in container run `python manage.py sapsynchronizer` 
- this will show you first logs of the costs for all sap data fetch 
- from logs you can check the dates in the sap-url
- logs for commitments fetch can't be seen locally, because there's no connection to sap locally
- in container run `python manage.py fetchsapdatabyyear --year 2023` 
- with this you can see logs for sap costs fetch for certain year (here 2023) 
- from logs you can check the dates in the sap-url
=> HKISD-257: change sap fetch start date

README.md, update-projecttypes.sql
- Add documentation about how to import new project type `preConstruction` (#229)
- Add API details
- Add ToC
- Readability
=> Docs: Update README with new project type import and overall readability

infraohjelmointi_api/serializers/ProjectCreateSerializer.py, infraohjelmointi_api/tests/test_Projects.py
When project phase is changed to be "warrantyPeriod", don't change the "programmed" value anymore to "False". 
When phase is "warrantyPeriod", programmed needs to be "True", to keep project still visible in hierarchy. 
Set the project's phase to be for example "Programmed", then programmed is true and project is visible in hierarchy. Then change the phase to be "Warranty Period". Check that programmed stays true and project is still visible in hierarchy. 
[Ticket](https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-178)
=> HKISD-178: make projects in warranty period visible in hierarchy

infraohjelmointi_api/serializers/SearchResultSerializer.py, infraohjelmointi_api/tests/test_Projects.py
If project belongs to a group, that is located in upper level in hierarchy, clicking the project from search result navigates to project's exact location, not the group's location. This is fixed with checking if project belongs to a group while creating a path where search result link will navigate. 
Create a project and add class informations to it. Then create a group to upper level in hierarchy and add the project in it. When you search this project and click the search result, planning view opens from the level where project locates. 
For example create a group to 8 03 Kadut ja liikenneväylät -> Perusparantaminen ja liikennejärjestelyt -> Joukkoliikenteen kehittäminen. And then create a project to 8 03 Kadut ja liikenneväylät -> Perusparantaminen ja liikennejärjestelyt -> …
=> HKISD-222: navigate to where project really locates from search

infraohjelmointi_api/tests/test_Projects.py, infraohjelmointi_api/views/ProjectViewSet.py
Empty groups were not in search results. That was cumbersome for user: the free search input field suggested also empty groups, but those were not in the result list. 
Ticket: [HKISD-222](https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-222&useStoredSettings=true)
Find or create an empty group and search it from search component. Search result now includes also empty groups.
=> HKISD-190: bring empty groups to search results

infraohjelmointi_api/services/utils/ProjectWiseDataMapper.py
- pw data mapper had two values for if project phase in infratool is `draftInitiation` and it resulted in an error caused by trying to send an array to pw when that project phase was selected in infratool
- fixed the `convert_to_pw_data` function so that if the result of mapping the data is an array, the second option is sent
- note: the unnecessary/wrong phase can't be removed completely from the code since some projects in pw might still have the phase and if we need to fetch project data from pw, we need to be able to convert it to a phase in infratool
- ticket: [https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-272](https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-272)
- can only be tested in dev …
=> HKISD-272/fix sending project phase to pw

infraohjelmointi_api/services/ProjectWiseService.py, infraohjelmointi_api/tests/management/commands/test_responsiblepersons.py, infraohjelmointi_api/tests/test_Projects.py, infraohjelmointi_api/views/ProjectViewSet.py
- ticket: [https://futurice.atlassian.net/browse/HKISD-224](https://futurice.atlassian.net/browse/HKISD-224)
- previously search only returned one project or group with same name even when there actually was more (no projects or groups with duplicate names where returned)
- you can test by creating multiple projects and groups with same name and see that search results has all of them when you search with the name
- you also need the UI PR for testing: [https://github.com/City-of-Helsinki/infraohjelmointi-ui/pull/319](https://github.com/City-of-Helsinki/infraohjelmointi-ui/pull/319)
=> HKISD-224: search groups and projects with same name

infraohjelmointi_api/views/ProjectViewSet.py
Bug was that when creating a budget for the first time to project, budgets went also to forced to frame view, even if forced to frame was locked. 
This fixes that. Budgets are moving to forced to frame only if it's not locked.
=> HKISD-275: When forcedToFrame is locked, prevent budget moving to forced to frame view

infraohjelmointi_api/serializers/ProjectGetSerializer.py
- Related UI-PR: https://github.com/City-of-Helsinki/infraohjelmointi-ui/pull/322
- Ticket: https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-268
- Description
- variable "startYear" is taken from planningView's year selector, and all sap values and current year's sap values are 
fetched from database to state based on that selected year.
- In planning view we want to show sap values only for the year that is selected in year selector as start year for time line
- In project card previously sap values were taken from state based on this start year. This was not wanted, since 
project card should show always current year's sap costs sum and total sum of sap costs and total sum of sap 
commitments, even if start year in planning view is something …
=> HKISD-268: get always current year in project card

infraohjelmointi_api/serializers/SearchResultSerializer.py
Link path in search results did not work in cases, where project was belonging to group that had location data. Previous solution did not take in count cases where projects were in group that has location info. Link in search results lead only to showing subClass in planning view. 
Ticket: https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-276&useStoredSettings=true
(Previous ticket: https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?search=222&selectedIssue=HKISD-222&useStoredSettings=true)
Create a project in 
'8 03 Kadut ja liikenneväylät', 'Perusparantaminen ja liikennejärjestelyt', 'Katujen peruskorjaukset', 'Eteläinen suurpiiri'. 
And also create a group to same location and put project to that group. 
The link from …
=> HKSID-276: fix link path in search results

infraohjelmointi_api/views/ProjectViewSet.py
- location filters in search used the locations from the hierarchy, which caused the lists to have multiple duplicates and missing options
- changed to use the same location options as the project card has, and that info is now compared to projectDistrict value on the Project model
- UI PR: https://github.com/City-of-Helsinki/infraohjelmointi-ui/pull/326
=> HKISD-119: fix filtering search based on project location

infraohjelmointi_api/permissions.py
Project area planners had permissions to open and modify project cards only in main class 8 08. Project area planners should have full permissions to see and modify projects under main class 8 08. Projects under other main classes project area planners should be able to see project cards and modify same fields that project managers have permission to modify. Permission ticket: https://helsinkisolutionoffice.atlassian.net/browse/IO-78. 
Notice: projectAreaPlanner does not have permissions to delete or create projects that goes under other than 8 08 main class. 
Ticket: https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-277
Set the roles in backend: in file BaseViewSet.py modify the permission_classes so that it includes only the projectAreaPlanner …
=> HKISD-277: fix permissions of project area planners

infraohjelmointi_api/tests/test_Api.py, infraohjelmointi_api/views/api/ApiClassesViewSet.py, infraohjelmointi_api/views/api/ApiDistrictsViewSet.py, infraohjelmointi_api/views/api/ApiGroupsViewSet.py, infraohjelmointi_api/views/api/ApiLocationsViewSet.py, infraohjelmointi_api/views/api/ApiProjectsViewSet.py, infraohjelmointi_api/views/api/utils.py
Includes changes to tackle Task kill and backend crashing issues when fetching data from all API endpoints at the same time. When data is fetched, API might crash because memory gets full.
- Use StreamingHttpResponse for API endpoints
- Use smaller chunk size for Projects endpoint
- Log how long time generating response took
- Update tests to correctly test endpoints with StreamingHttpResponse
=> feat: HKISD-279 use StreamingHttpResponse for API endpoints

infraohjelmointi_api/views/api/ApiProjectsViewSet.py
Duplicated decorator caused endpoint /api/projects/ crashing. This fix removes unnecessary Swagger decorator.
=> fix: HKISD-279 remove duplicated swagger decorator

project/settings.py
Decreasing the size of the cache to 300, which is default value. There's no need anymore for extra large cache.
=> HKISD-279: decrease chache size from 6000 to 300

infraohjelmointi_api/views/ProjectViewSet.py
Add logging to getProjects endpoint. If needed, logging can be reduced afterwards. 
Logging is added to help investigating report downloading issues in production.
=> HKISD-279: add logging to ProjectViewSet to investigate getProjects

Dockerfile
When there is a need to build docker image again, with current docker file it takes some time before all needed packages are installed.
Refactored file adds more build steps. With this, docker build can use cached layers for `yum` command. Previously one step included `yum` and `pip` commands, which took 119s to create.
`docker compose up --build`
Before
```output
[+] Building 124.8s (10/10) FINISHED                                                                                       docker:default
=> [api internal] load build definition from Dockerfile                                                                             0.0s
=> => transferring dockerfile: 1.16kB                                                                                               0.0s
=> [api internal] …
```
=> refactor: use cache layers to build docker image quicker

infraohjelmointi_api/permissions.py
Project manager is not allowed to delete projects. 
Ticket: https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-270
Related PR in frontend: https://github.com/City-of-Helsinki/infraohjelmointi-ui/pull/325
Set the roles in backend: in file BaseViewSet.py modify the permission_classes so that it includes only the projectManager role. In frontend: in file AuthSlice.ts uncomment from the ad_groups the projectManager group. This will simulate the case when user has only projectManager role.
=> HKISD-270: fix project managers permissions

infraohjelmointi_api/tests/test_Api.py, infraohjelmointi_api/views/api/ApiGroupsViewSet.py, infraohjelmointi_api/views/api/ApiProjectsViewSet.py, infraohjelmointi_api/views/api/utils.py
- use asynchronous and not synchronous iterators with streamingHttpResponse
- update api/projects tests to correctly handle streamingHttpResponse
- remove unnecessary imports
=> Fix/Api streamingHttpResponse iterators

infraohjelmointi_api/services/ProjectFinancialService.py, infraohjelmointi_api/views/ProjectViewSet.py
When project finance values were changed, the project's `updatedDate` value was updated, but the `updatedDate` for the project financials was not."
https://futurice.atlassian.net/browse/HKISD-97
=> fix: HKISD-97 update updatedDate when project finance value changes

infraohjelmointi_api/serializers/FinancialSumSerializer.py, infraohjelmointi_api/tests/test_BalkSums.py, infraohjelmointi_api/tests/test_FinancialSumSerializer.py
Fixed FinancialSumSerializer logic that incorrectly flagged budget overlaps when child budgets sum equaled parent frame budget
https://helsinkisolutionoffice.atlassian.net/browse/IO-743
=> fix: IO-743 Coordination view false positive budget overlap warnings

infraohjelmointi_api/serializers/FinancialSumSerializer.py, infraohjelmointi_api/tests/test_BalkSums.py
Fixed problem where projects with groups were not being properly filtered based on whether the group belonged to the location hierarchy being queried. This created a situation where location appeared to have budget sums from projects that were not displayed under them.
Now projects are included for location if they have no group or have a group whose `locationRelation` belongs to the same location hierarchy.
=> fix: IO-738 Wrong budget sums for locations
