City-of-Helsinki/infraohjelmointi-api

infraohjelmointi_api/serializers.py
infraohjelmointi_api/tests/test_Projects.py

- Added validation for projectLocation and projectClass fields 
- Validation checks that both fields have values that are compatible with each other
- Wrote tests for these changes
- Validation has been written according to the rules defined for subclasses and locations in the Excel in the story board.

Story/io 243/new level under subclass

---

infraohjelmointi_api/serializers.py
infraohjelmointi_api/tests/test_Projects.py

Added pwFolderLink to Project Patch request response

Added pwFolderLink to projectPatch request response

---

infraohjelmointi_api/serializers.py
infraohjelmointi_api/tests/test_Projects.py
infraohjelmointi_api/views.py

- Added district to path field in search results response
- Wrote test to check path

Story/io 272/new breadcrumbs path

---

infraohjelmointi_api/serializers.py
infraohjelmointi_api/tests/test_Projects.py

Added programmed field to search results response
Field is null for Locations, Groups and Classes
For projects its either True or False
Wrote tests

Search results response `programmed` field addition

---

infraohjelmointi_api/management/commands/util/BudgetFileHandler.py
infraohjelmointi_api/management/commands/util/PlanningFileHandler.py
infraohjelmointi_api/services/ProjectPhaseService.py

- Made changes to PlanningFileHandler and BudgetFileHandler to have phase information and correct timeline dates populated in DB

Story/io 333/migrating new excel to infra

---

infraohjelmointi_api/serializers/ProjectGroupSerializer.py
infraohjelmointi_api/tests/test_ProjectGroups.py
infraohjelmointi_api/views.py

- Created a coordinator endpoint for project-groups
- Endpoint returns groups with coordinator location and classes
- Wrote test

Story/io 355/adding groups in coordination

---

infraohjelmointi_api/serializers/ProjectHashtagSerializer.py
infraohjelmointi_api/services/ProjectHashTagService.py
infraohjelmointi_api/validators/ProjectHashtagValidators/HashtagNameValidator.py
infraohjelmointi_api/validators/ProjectHashtagValidators/__init__.py

Changed error code for hashtag duplicate name error

Fixed validation error code for hashtag duplicate error

---

infraohjelmointi_api/management/commands/util/BudgetFileHandler.py
infraohjelmointi_api/views/SapCostViewSet.py

- Added new endpoint for sap costs to get sap costs by year from DB
- Fixed a note updatedBy in budgetfile handler

Added custom action to sapcost viewset for fetching sap costs by year

---

README.md

- Updated readme with data import and sources information

Added data sources information to readme.md

---

infraohjelmointi_api/management/commands/util/BudgetFileHandler.py
infraohjelmointi_api/models/Project.py

- Changed FavPerson and Hashtag models so that they don't give errors while running the script if value put to that field is null
- Changed one logger message level to be info instead of error, cause it was actually not an error

fix models that gave errors and change one log message to be info

---

infraohjelmointi_api/views/ProjectClassViewSet.py

Check if the value is empty, and if so, don't save the object

don't save value if empty

---

infraohjelmointi_api/management/commands/util/BudgetFileHandler.py

- don't push numbers under correct years: starting from 2024
- read correctly projectwise number
- read correctly notes

read projectwise number correctly

---

README.md

Added instruction for how to do a production release

add innstructions for production release

---

infraohjelmointi_api/management/commands/responsiblepersons.py

- create a script to add new responsible persons
- imports an excel file, which includes person information `firstName | lastName` per row

create script to add responsible persons

---

infraohjelmointi_api/management/commands/responsiblepersons.py

- When codesmell issue was fixed, attribute names were unintentionally changed

fix responsiblepersons attributes

---

.gitignore
README.md
fix-database.sql
infraohjelmointi_api/management/commands/util/hierarchy.py
infraohjelmointi_api/services/SapApiService.py
infraohjelmointi_api/tests/test_Projects.py
sonar-project.properties

- keep Suurpiiri name on projectLocation names and paths
- update README to include missing information
- details what to do after container is running
- missing import scripts
- fix syntaxWarning with a literal -error
- don't add Excel files' Alternate Data Stream -file
- add SQL file which fixes typos and missing suurpiiri -texts

HKISD-24: Keep Suurpiiri name

---

infraohjelmointi_api/management/commands/util/hierarchy.py

coming features will affect database and hierarchy importer. With this we can set dev to the same state as main branch, import the data, and make another merge with new features to test will database changes go well on dev environment.

rollback file to match the main branch before coming changes

---

.gitignore
README.md
fix-database.sql
infraohjelmointi_api/management/commands/util/BudgetFileHandler.py
infraohjelmointi_api/management/commands/util/hierarchy.py
infraohjelmointi_api/services/SapApiService.py
infraohjelmointi_api/tests/test_Projects.py
sonar-project.properties

- modified scripts for adding missing divisions
- modified and added scripts/commands to fix typos and incorrect numberings of divisions/districts

Release 29.1.2024

---

infraohjelmointi_api/services/ProjectDistrictService.py
infraohjelmointi_api/services/ProjectWiseService.py
infraohjelmointi_api/services/utils/ProjectWiseDataMapper.py

- ticket: https://futurice.atlassian.net/browse/HKISD-29
- fixed project's location update to PW
- fixed pw update function crashing when one field in data was not supported
- added a check for sending the post request only if there's new data to update to pw

HHISD-29/fix pw sync

---

infraohjelmointi_api/serializers/BaseMeta.py
infraohjelmointi_api/views/ProjectViewSet.py

Before it was defined, that when giving response to frontend when posting/patching projectinfo, updatedDate was excluded of response. 
Now this response includes also updatedDate and it's in the response to frontend.

Hkisd 44/fix project card saving

---

infraohjelmointi_api/services/utils/ProjectWiseDataMapper.py

- Ticket: https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-64
- If user was trying to delete responsible person from a project that has PW id, it was not possible, cause pw sync function was trying to get the empty value from the person table and encountered an error cause of that

HKISD-64: fix responsible person sync to pw

---

README.md

- Use similar filenames in instruction as what files has
- Files on password and file manager will be updated later
- Hide some of scripts under dropdown menu to make easier to follow steps and run the correct commands/scripts  
- Reorganize structure

Make instructions more clear

---

infraohjelmointi_api/management/commands/util/locationFileHandler.py

- with this the script will create district on infraohjelmointi_api_projectdistrict even when district and division names are the same
- should be merged to develop after #111 is merged to develop and main branches

create division even district and division name are the same

---

.gitignore
README.md
infraohjelmointi_api/management/commands/util/hierarchy.py
infraohjelmointi_api/management/commands/util/locationFileHandler.py

- Save finance data correctly if it is zero
- Set the cache for 2h instead of 24h

Release 20.02.2024

---

docker-entrypoint.sh

- setting http_timeout to be 60 sec instead of the default

fix: add http_timeout for daphne to fix timeout error

---

docker-entrypoint.sh

Reverts City-of-Helsinki/infraohjelmointi-api#130

Revert "fix: add http_timeout for daphne to fix timeout error"

---

infraohjelmointi_api/views/ProjectViewSet.py

- did some optimizing for fetching coordinator projects
- dropped queries per project from 12 to 8

refactor: optimize fetching coordinator projects

---

infraohjelmointi_api/serializers/ProjectGetSerializer.py
infraohjelmointi_api/serializers/ProjectWithFinancesSerializer.py
infraohjelmointi_api/views/ProjectViewSet.py

- added more optimizing for fetching projects

refactor: do some more optimizing for fetching projets

---

.gitignore
README.md
infraohjelmointi_api/management/commands/util/hierarchy.py
infraohjelmointi_api/management/commands/util/locationFileHandler.py

- optimisations for fetching projects (fixes the timeout error we had when downloading reports)

Release 21.3.2024

---

infraohjelmointi_api/serializers/ProjectGetSerializer.py
infraohjelmointi_api/serializers/ProjectWithFinancesSerializer.py
infraohjelmointi_api/views/ProjectViewSet.py

Reverts City-of-Helsinki/infraohjelmointi-api#135

Revert "Release 21.3.2024"

---

infraohjelmointi_api/serializers/ProjectWithFinancesSerializer.py

- fixes creating a new project. It failed cause a new project doesn't have finances_filtered attribute yet

fix: creating a new project failing

---

infraohjelmointi_api/serializers/ProjectGetSerializer.py
infraohjelmointi_api/serializers/ProjectWithFinancesSerializer.py
infraohjelmointi_api/views/ProjectViewSet.py

Reverts City-of-Helsinki/infraohjelmointi-api#136

Revert the revert

---

infraohjelmointi_api/services/utils/ProjectWiseDataMapper.py

- PW data mapping function didn't convert empty dates correctly

fix: issue with removing dates from project form and saving to PW

---

infraohjelmointi_api/serializers/ProjectWithFinancesSerializer.py
infraohjelmointi_api/services/utils/ProjectWiseDataMapper.py

- fixes an issue with converting empty dates in project form to PW data

Fix: update empty dates to PW

---

infraohjelmointi_api/permissions.py
infraohjelmointi_api/services/utils/ProjectWiseDataMapper.py

- fixed an issue where project area planners were not able to edit projects or groups under 808

Fix: editing groups and projects as a project area planner

---

infraohjelmointi_api/serializers/FinancialSumSerializer.py
infraohjelmointi_api/signals.py
infraohjelmointi_api/views/ConstructionPhaseDetailViewSet.py
infraohjelmointi_api/views/ConstructionPhaseViewSet.py
infraohjelmointi_api/views/PlanningPhaseViewSet.py
infraohjelmointi_api/views/ProjectAreaViewSet.py
infraohjelmointi_api/views/ProjectCategoryViewSet.py
infraohjelmointi_api/views/ProjectClassViewSet.py
infraohjelmointi_api/views/ProjectGroupViewSet.py
infraohjelmointi_api/views/ProjectPhaseViewSet.py
infraohjelmointi_api/views/ProjectPriorityViewSet.py
infraohjelmointi_api/views/ProjectQualityLevelViewSet.py
infraohjelmointi_api/views/ProjectResponsibleZoneViewSet.py
infraohjelmointi_api/views/ProjectRiskViewSet.py
infraohjelmointi_api/views/ProjectTypeViewSet.py
project/settings.py

- ticket: [https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-83](https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-83)
- removed cache from backend
- added optimizations for fetching classes and groups
- removed pandas from FinancialSumSerializer, cause it was causing a lot of slowness and it wasn't really needed for calculating the frameBudgetOverlap for classes

HKISD-83/fix cache issues

---

infraohjelmointi_api/models/Project.py
infraohjelmointi_api/permissions.py
infraohjelmointi_api/serializers/WhoAmISerializer.py

- ticket: https://futurice.atlassian.net/browse/HKISD-138
- added new user role based on the ticket
- the new katselijat_muut role should have the same permissions as the katselijat role
- for testing, both backend and frontend need to be in the feature branches and other roles need to be commented out

feat: HKISD-138 add new user role katselijat_muut

---

infraohjelmointi_api/tests/test_BalkSums.py
infraohjelmointi_api/tests/test_Projects.py

- fix failing tests
- use correct financial year
- use correct response codes
- remove unused imports

tests: fix failing tests

---

docker-entrypoint.sh

Related ticket: https://futurice.atlassian.net/jira/servicedesk/projects/HKI/queues/custom/238/HKI-184
Same increase of the header size was done already in the UI, this PR will do the same to backend also. 
(UI change is already in production https://github.com/City-of-Helsinki/infraohjelmointi-ui/pull/266)

HKISD-184: increase the header size

---

Dockerfile

fetch PostgreSQL GPG key using curl

fix fetch PostgreSQL GPG key using curl

---

project/settings.py

Reverts City-of-Helsinki/infraohjelmointi-api#176

Revert "fix: HKISD-184 add configurable TWISTED_MAX_LINE_LENGTH setting"

---

project/settings.py

Reverts City-of-Helsinki/infraohjelmointi-api#177

Revert "Revert "fix: HKISD-184 add configurable TWISTED_MAX_LINE_LENGTH setting""

---

requirements.txt

HKISD-191 Upgrade Django to version 4.2
For testing:
`docker-compose up --build --force-recreate`
In the container check if updated:
`python -m django --version`
Run tests according to READ.ME

HKISD-191 Upgrade Django to version 4.2

---

infraohjelmointi_api/management/commands/locationimporter.py
sonar-project.properties

- add a script to create "Eri kaupunginosia" division under every district
- will be removed once divisions are created

HKISD-159 add script to add eri kaupunginosia location

---

infraohjelmointi_api/services/SapApiService.py
infraohjelmointi_api/tests/test_SAP.py

https://futurice.atlassian.net/browse/HKISD-149
Currently, SAP data is pulled from the past five years up to now. With this change, we check project planning year and use that for fetch the data.
If the SAP ID has multiple projects, the code checks earliest project plannin year and uses that.
As a default, the data will be fetched from previous year to this year (2023-2024).

feat: HKISD-149 fetch SAP data based on earliest planning start year

---

infraohjelmointi_api/services/ProjectWiseService.py
infraohjelmointi_api/tests/test_ProjectWiseService.py

Reverts City-of-Helsinki/infraohjelmointi-api#185

Revert "HKISD-171/don't import phone numbers or titles"

---

infraohjelmointi_api/management/commands/responsiblepersons.py

Modify instructions that help when adding responsible persons. Add mention about email.

fix: HKISD-214 fix instructions when addin new responsible person

---

infraohjelmointi_api/views/ProjectGroupViewSet.py

- added the possibility to fetch forced to frame finances for groups

HKISD-218 add forced to frame data fetching for groups

---

infraohjelmointi_api/services/SapApiService.py
infraohjelmointi_api/tests/test_SAP.py

Reverts City-of-Helsinki/infraohjelmointi-api#191

Revert "Revert "feat: HKISD-149 fetch SAP data based on earliest planning start year""

---

infraohjelmointi_api/services/SapApiService.py

- ticket: [https://futurice.atlassian.net/browse/HKISD-149](https://futurice.atlassian.net/browse/HKISD-149)
- was previously in dev environment but there was issues mentioned in the comment on the ticket and thus this was reverted from dev (issue should now be fixed)
- here is the reverted PR: [https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/191](https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/191) (needs to be re-reverted first to solve conflicts in this PR 😄 )

HKISD-149: fetching SAP data based on the earliest planning start year

---

infraohjelmointi_api/services/SapApiService.py

Reverts City-of-Helsinki/infraohjelmointi-api#204

Revert "add logging"

---

infraohjelmointi_api/services/SapApiService.py

HKISD-149: add logging

---

README.md

Make readme more clear and add missing script commands.

Doc: fix readme

---

infraohjelmointi_api/services/SapApiService.py

HKISD-229: fix bug in error logging

---

infraohjelmointi_api/services/SapApiService.py

Previously commitments were always fetched until end of the current year. E.g. in December 2024 the end date for fetch was 1.1.2025. 
Now a new parameter is passed for method `__fetch_costs_and_commitments_from_sap` to tell, if the fetch is going to be all sap values or only current year values. 
When parameter `all_sap_commitments` is true (meaning fetch is going to be done for all sap values), the end date for commitment fetch is changed to be budat_end + 5 years. E.g. in December 2024 this end date would be 1.1.2030. 
https://helsinkisolutionoffice.atlassian.net/jira/software/c/projects/IO/boards/302?selectedIssue=IO-418

IO-418: fetch all sap commitments until current year + 5 years

---

infraohjelmointi_api/tests/management/commands/test_responsiblepersons.py

- test works again :)
- was broken after removing pandas

Fix test_populate_db_with_excel test

---

infraohjelmointi_api/serializers/SearchResultSerializer.py

Changes related to PR https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/233 had error. This is fixed by adding variable group to None as default. 
Ticket: https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-271&useStoredSettings=true

HKISD-271: fix internal server error

---

infraohjelmointi_api/tests/test_Projects.py

Additional PR to fix test related to previous PR https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/240

HKISD-275: fix tests

---

infraohjelmointi_api/views/ProjectViewSet.py

added filtering searched projects based on pw id and construction person
ticket: [added search fields for pw id and construction person
ticket: https://helsinkisolutionoffice.atlassian.net/browse/IO-408](https://helsinkisolutionoffice.atlassian.net/browse/IO-408)
UI PR: [https://github.com/City-of-Helsinki/infraohjelmointi-ui/pull/328](https://github.com/City-of-Helsinki/infraohjelmointi-ui/pull/328)

IO-408/new fields for search

---

infraohjelmointi_api/services/SapApiService.py

This PR adds catch for error MultipleObjectsReturned. Error and problematic sapId will be logged and all other items will be saved to database, even if this error will occur. 
Also improve logging by removing unnecessary log for errors and changing one logging from debug to info.

HKISD-286: add catch for multipleObjectsReturned and improve logging

---

infraohjelmointi_api/views/api/ApiClassesViewSet.py
infraohjelmointi_api/views/api/ApiDistrictsViewSet.py
infraohjelmointi_api/views/api/ApiGroupsViewSet.py
infraohjelmointi_api/views/api/ApiLocationsViewSet.py
infraohjelmointi_api/views/api/ApiProjectsViewSet.py
infraohjelmointi_api/views/api/utils.py

- Create function for API endpoints to generate Response
- API logging (user, endpoint)
- documentation
- format API files

HKISD-279/api-streaminghttpresponse-changes

---

infraohjelmointi_api/serializers/ProjectGetSerializer.py
infraohjelmointi_api/tests/management/commands/test_responsiblepersons.py
infraohjelmointi_api/tests/test_Projects.py
infraohjelmointi_api/views/ProjectViewSet.py

Reverts City-of-Helsinki/infraohjelmointi-api#251

Revert "Revert "Release 3.3.2025""

---

infraohjelmointi_api/views/api/ApiClassesViewSet.py
infraohjelmointi_api/views/api/ApiProjectsViewSet.py
infraohjelmointi_api/views/api/utils.py

Use measures developed in #266 to optimize some PowerBI endpoints. The following endpoints are affected:
- GET /api/projects/
- GET /api/classes/
The remaining PowerBI endpoints were not looked at, though there might be some room to optimize them as well.

HKISD-279: Make some PowerBI endpoints faster

---

infraohjelmointi_api/serializers/ProjectGetSerializer.py
infraohjelmointi_api/tests/management/commands/test_responsiblepersons.py
infraohjelmointi_api/tests/test_Projects.py
infraohjelmointi_api/views/ProjectViewSet.py

Reverts City-of-Helsinki/infraohjelmointi-api#263

Revert "Revert "Revert "Release 3.3.2025"""

---

.env.template
docker-entrypoint.sh
requirements.txt

- changed daphne to uvicorn to prevent daphnes "took too long to shut down and was killed." error

use uvicorn instead of daphne

---

infraohjelmointi_api/serializers/ProjectGetSerializer.py
infraohjelmointi_api/tests/management/commands/test_responsiblepersons.py
infraohjelmointi_api/tests/test_Projects.py
infraohjelmointi_api/views/ProjectViewSet.py

Reverts City-of-Helsinki/infraohjelmointi-api#272

Revert "Revert "Revert "Revert "Release 3.3.2025""""

---

infraohjelmointi_api/tests/test_Api.py
infraohjelmointi_api/views/api/ApiClassesViewSet.py
infraohjelmointi_api/views/api/ApiDistrictsViewSet.py
infraohjelmointi_api/views/api/ApiGroupsViewSet.py
infraohjelmointi_api/views/api/ApiLocationsViewSet.py
infraohjelmointi_api/views/api/ApiProjectsViewSet.py
infraohjelmointi_api/views/api/utils.py

Reverts City-of-Helsinki/infraohjelmointi-api#271

Revert "Revert "Release 27.3.2025""

---

infraohjelmointi_api/serializers/FinancialSumSerializer.py
infraohjelmointi_api/serializers/ProjectFinancialSerializer.py
infraohjelmointi_api/serializers/ProjectGetSerializer.py
infraohjelmointi_api/tests/test_Api.py
infraohjelmointi_api/views/ProjectClassViewSet.py
infraohjelmointi_api/views/ProjectViewSet.py
infraohjelmointi_api/views/api/ApiClassesViewSet.py
infraohjelmointi_api/views/api/ApiDistrictsViewSet.py
infraohjelmointi_api/views/api/ApiGroupsViewSet.py
infraohjelmointi_api/views/api/ApiLocationsViewSet.py
infraohjelmointi_api/views/api/ApiProjectsViewSet.py
infraohjelmointi_api/views/api/utils.py
project/settings.py

Reverts City-of-Helsinki/infraohjelmointi-api#270

Revert "Revert "Release 3.4.2025""

---

infraohjelmointi_api/views/ProjectViewSet.py

- Added more logging for serializing the paginated project response data

Add logging for fetching projects

---

infraohjelmointi_api/serializers/ProjectGetSerializer.py
infraohjelmointi_api/views/ProjectViewSet.py

- changed fetching sap values to make loading projects faster (similar approach than for finances in this PR: https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/266)

optimized fetching current year sap values for projects

---

infraohjelmointi_api/serializers/ProjectGetSerializer.py
infraohjelmointi_api/services/SapCurrentYearService.py

- fixed an issue where project id was not checked when fetching sap data

fix multiple current year values being returned

---

.env.template

This PR changes the PW link to be in the new format in file .env.template.

HKISD-274: change PW-folder link

---

infraohjelmointi_api/services/SapApiService.py

- added logging to see what data the sap response contains before we start to filter it
- only intended to use in dev environment where we have one project with working SAP id
- can't test in local cause there's no SAP connection

add logging the sap response

---

infraohjelmointi_api/permissions.py
infraohjelmointi_api/serializers/WhoAmISerializer.py

ticket: [https://helsinkisolutionoffice.atlassian.net/browse/IO-460](https://helsinkisolutionoffice.atlassian.net/browse/IO-460)
UI PR: [https://github.com/City-of-Helsinki/infraohjelmointi-ui/pull/377](https://github.com/City-of-Helsinki/infraohjelmointi-ui/pull/377)

IO-460: add viewer user role

---

infraohjelmointi_api/permissions.py
infraohjelmointi_api/serializers/WhoAmISerializer.py
update-class-hierarchy.sql

- IO-460: add viewer user role

release 13.6.2025
